name:                taskell2
version:             0.1.0.0
github:              smallhadroncollider/taskell2
license:             BSD3
author:              Small Hadron Collider / Mark Wales
maintainer:          mark@smallhadroncollider.com
copyright:           Small Hadron Collider / Mark Wales

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/smallhadroncollider/taskell2#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

library:
  source-dirs: src
  dependencies:
  - hashable
  - microlens-th

executables:
  taskell2:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - taskell2
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  taskell2-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - taskell2
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

benchmarks:
  criterion-benchmarks:
    main:                Main.hs
    source-dirs:         benchmarks
    dependencies:
    - taskell2
    - criterion
